import type { ThemeChoice, ThemeConfig, ThemeMarkers } from '@/types';

export type { ThemeConfig };

// Theme-specific marker symbols/colors
export const THEME_MARKERS: Record<ThemeChoice, ThemeMarkers> = {
  light: {
    pending: '○',
    inProgress: '◑',
    completed: '●',
    approved: '✅',
  },
  flower: {
    pending: '🌱',
    inProgress: '🌿',
    completed: '🌸',
    approved: '💐',
  },
  pastel: {
    pending: '○',
    inProgress: '◑',
    completed: '●',
    approved: '✅',
  },
  sports: {
    pending: '◇',
    inProgress: '◈',
    completed: '◆',
    approved: '⭐',
  },
  dark: {
    pending: '◇',
    inProgress: '◈',
    completed: '◆',
    approved: '⭐',
  },
  mario: {
    pending: '🧱',
    inProgress: '❓',
    completed: '🍄',
    approved: '🌟',
  },
};

// Flat theme configurations
export const THEMES: Record<ThemeChoice, ThemeConfig> = {
  light: {
    name: 'Light',
    emoji: '☀️',
    navVariant: 'light',
    pageBg: 'bg-slate-100',
    cardBg: 'bg-white',
    cardBorder: 'border-slate-200',
    headingColor: 'text-slate-900',
    bodyText: 'text-slate-700',
    mutedText: 'text-slate-500',
    button: 'bg-sky-600 hover:bg-sky-700',
    progressGradient: 'from-sky-400 to-sky-600',
    progressTrack: 'bg-slate-100',
    sectionCheckedBg: 'bg-sky-50',
    sectionCheckedBorder: 'border-sky-300',
    sectionCheckedText: 'text-sky-900',
    sectionUncheckedBg: 'bg-white',
    sectionUncheckedBorder: 'border-slate-200',
    checkboxActiveBg: 'bg-sky-500',
    checkboxActiveBorder: 'border-sky-500',
    checkboxInactiveBg: 'bg-white',
    checkboxInactiveBorder: 'border-slate-300',
    inputBg: 'bg-white',
    inputBorder: 'border-slate-200',
    inputFocus: 'focus:ring-sky-500',
    inputText: 'text-slate-900',
    labelColor: 'text-slate-500',
    selectBg: 'bg-white',
    themeButtonActive: 'border-sky-500 bg-sky-50 text-sky-800',
    themeButtonInactive: 'border-slate-200 text-slate-600 hover:border-slate-300',
  },

  flower: {
    name: 'Flower',
    emoji: '🌸',
    navVariant: 'light',
    pageBg: 'bg-gradient-to-br from-pink-300 via-rose-200 to-fuchsia-200',
    cardBg: 'bg-pink-50',
    cardBorder: 'border-pink-300',
    headingColor: 'text-rose-900',
    bodyText: 'text-rose-800',
    mutedText: 'text-pink-500',
    button: 'bg-fuchsia-600 hover:bg-fuchsia-700',
    progressGradient: 'from-pink-400 to-fuchsia-500',
    progressTrack: 'bg-pink-100',
    sectionCheckedBg: 'bg-rose-100',
    sectionCheckedBorder: 'border-fuchsia-400',
    sectionCheckedText: 'text-rose-900',
    sectionUncheckedBg: 'bg-pink-50',
    sectionUncheckedBorder: 'border-pink-200',
    checkboxActiveBg: 'bg-fuchsia-500',
    checkboxActiveBorder: 'border-fuchsia-500',
    checkboxInactiveBg: 'bg-white',
    checkboxInactiveBorder: 'border-pink-300',
    inputBg: 'bg-white',
    inputBorder: 'border-pink-300',
    inputFocus: 'focus:ring-fuchsia-400',
    inputText: 'text-slate-900',
    labelColor: 'text-pink-600',
    selectBg: 'bg-white',
    themeButtonActive: 'border-fuchsia-500 bg-pink-50 text-fuchsia-800',
    themeButtonInactive: 'border-pink-200 text-pink-700 hover:border-pink-400',
  },

  pastel: {
    name: 'Pastel',
    emoji: '🎨',
    navVariant: 'light',
    pageBg: 'bg-gradient-to-br from-violet-200 via-purple-100 to-indigo-200',
    cardBg: 'bg-purple-50',
    cardBorder: 'border-violet-300',
    headingColor: 'text-violet-900',
    bodyText: 'text-purple-800',
    mutedText: 'text-violet-500',
    button: 'bg-violet-600 hover:bg-violet-700',
    progressGradient: 'from-violet-400 to-indigo-500',
    progressTrack: 'bg-violet-100',
    sectionCheckedBg: 'bg-violet-100',
    sectionCheckedBorder: 'border-violet-400',
    sectionCheckedText: 'text-violet-900',
    sectionUncheckedBg: 'bg-purple-50',
    sectionUncheckedBorder: 'border-violet-200',
    checkboxActiveBg: 'bg-violet-500',
    checkboxActiveBorder: 'border-violet-500',
    checkboxInactiveBg: 'bg-white',
    checkboxInactiveBorder: 'border-violet-300',
    inputBg: 'bg-white',
    inputBorder: 'border-violet-200',
    inputFocus: 'focus:ring-violet-400',
    inputText: 'text-slate-900',
    labelColor: 'text-violet-600',
    selectBg: 'bg-white',
    themeButtonActive: 'border-violet-500 bg-violet-50 text-violet-800',
    themeButtonInactive: 'border-violet-200 text-violet-700 hover:border-violet-400',
  },

  sports: {
    name: 'Sports',
    emoji: '⚽',
    navVariant: 'dark',
    pageBg: 'bg-zinc-950',
    cardBg: 'bg-zinc-900',
    cardBorder: 'border-orange-500',
    headingColor: 'text-white',
    bodyText: 'text-zinc-300',
    mutedText: 'text-zinc-400',
    button: 'bg-orange-500 hover:bg-orange-600',
    progressGradient: 'from-orange-400 to-red-600',
    progressTrack: 'bg-zinc-700',
    sectionCheckedBg: 'bg-zinc-800',
    sectionCheckedBorder: 'border-orange-400',
    sectionCheckedText: 'text-orange-300',
    sectionUncheckedBg: 'bg-zinc-900',
    sectionUncheckedBorder: 'border-zinc-700',
    checkboxActiveBg: 'bg-orange-500',
    checkboxActiveBorder: 'border-orange-500',
    checkboxInactiveBg: 'bg-zinc-800',
    checkboxInactiveBorder: 'border-zinc-600',
    inputBg: 'bg-zinc-800',
    inputBorder: 'border-zinc-700',
    inputFocus: 'focus:ring-orange-500',
    inputText: 'text-white',
    labelColor: 'text-orange-400',
    selectBg: 'bg-zinc-800',
    themeButtonActive: 'border-orange-500 bg-zinc-800 text-orange-400',
    themeButtonInactive: 'border-zinc-700 text-zinc-400 hover:border-zinc-500',
  },

  dark: {
    name: 'Dark',
    emoji: '🌙',
    navVariant: 'dark',
    pageBg: 'bg-slate-950',
    cardBg: 'bg-slate-900',
    cardBorder: 'border-slate-700',
    headingColor: 'text-white',
    bodyText: 'text-slate-300',
    mutedText: 'text-slate-500',
    button: 'bg-violet-600 hover:bg-violet-700',
    progressGradient: 'from-violet-500 to-indigo-600',
    progressTrack: 'bg-slate-800',
    sectionCheckedBg: 'bg-slate-800',
    sectionCheckedBorder: 'border-violet-500',
    sectionCheckedText: 'text-violet-300',
    sectionUncheckedBg: 'bg-slate-900',
    sectionUncheckedBorder: 'border-slate-700',
    checkboxActiveBg: 'bg-violet-500',
    checkboxActiveBorder: 'border-violet-500',
    checkboxInactiveBg: 'bg-slate-800',
    checkboxInactiveBorder: 'border-slate-600',
    inputBg: 'bg-slate-800',
    inputBorder: 'border-slate-700',
    inputFocus: 'focus:ring-violet-500',
    inputText: 'text-white',
    labelColor: 'text-slate-400',
    selectBg: 'bg-slate-800',
    themeButtonActive: 'border-violet-500 bg-slate-800 text-violet-400',
    themeButtonInactive: 'border-slate-700 text-slate-400 hover:border-slate-600',
  },

  mario: {
    name: 'Mario',
    emoji: '🍄',
    navVariant: 'dark',
    pageBg: '#5C94FC',
    cardBg: '#F8D870',
    cardBorder: 'border-black border-b-4 border-r-4',
    headingColor: '#E4000F',
    bodyText: 'text-black',
    mutedText: 'text-gray-700',
    button: 'bg-red-600 hover:bg-red-700 border-2 border-black',
    progressGradient: 'from-yellow-400 to-orange-500',
    progressTrack: 'bg-gray-300',
    sectionCheckedBg: 'bg-red-100',
    sectionCheckedBorder: 'border-red-500',
    sectionCheckedText: 'text-red-700',
    sectionUncheckedBg: 'bg-yellow-100',
    sectionUncheckedBorder: 'border-gray-300',
    checkboxActiveBg: 'bg-red-600',
    checkboxActiveBorder: 'border-red-600',
    checkboxInactiveBg: 'bg-white',
    checkboxInactiveBorder: 'border-gray-400',
    inputBg: 'bg-white',
    inputBorder: 'border-black border-2',
    inputFocus: 'focus:ring-red-500',
    inputText: 'text-black',
    labelColor: 'text-gray-800',
    selectBg: 'bg-white',
    themeButtonActive: 'border-red-500 bg-red-100 text-red-800',
    themeButtonInactive: 'border-gray-300 text-gray-600 hover:border-gray-400',
  },
};

// Helper function to get both config and markers for a theme
export function getThemeAspects(theme: ThemeChoice): {
  config: ThemeConfig;
  markers: ThemeMarkers;
} {
  return {
    config: THEMES[theme],
    markers: THEME_MARKERS[theme],
  };
}

export const THEME_ORDER: ThemeChoice[] = ['light', 'flower', 'pastel', 'sports', 'dark', 'mario'];

// Status-specific colors for the progress checklist
export const statusColors = {
  pending: {
    borderColor: 'border-gray-300',
    bgColor: 'bg-gray-50',
    textColor: 'text-gray-700',
    badgeBg: 'bg-gray-200',
    badgeText: 'text-gray-800',
  },
  'in-progress': {
    borderColor: 'border-blue-300',
    bgColor: 'bg-blue-50',
    textColor: 'text-blue-700',
    badgeBg: 'bg-blue-200',
    badgeText: 'text-blue-800',
  },
  completed: {
    borderColor: 'border-green-300',
    bgColor: 'bg-green-50',
    textColor: 'text-green-700',
    badgeBg: 'bg-green-200',
    badgeText: 'text-green-800',
  },
  rejected: {
    borderColor: 'border-red-300',
    bgColor: 'bg-red-50',
    textColor: 'text-red-700',
    badgeBg: 'bg-red-200',
    badgeText: 'text-red-800',
  },
};
